#!/usr/bin/env python3
"""Add unique, substantive sections to pillar pages under 999 visible words."""
import re

def words(p):
    html = open(p).read()
    m = re.search(r'<body.*?</body>', html, re.S)
    t = m.group(0) if m else html
    t = re.sub(r'<script.*?</script>|<style.*?</style>|<!--.*?-->', '', t, flags=re.S)
    return len(re.sub(r'<[^>]+>', ' ', t).split())

ADDS = {
"analyzing-viral-video-metrics.html": [
 ("The four metrics that predict virality early","Full-history stats confirm what already happened; prediction requires leading indicators measured in the first 24 hours. Hook rate (viewers surviving three seconds) predicts whether the algorithm keeps testing your video. Average percentage viewed flags pacing problems before they cap reach. Share-rate-per-thousand-views is the single best proxy for the send-this-to-a-friend quality that drives exponential spread. Follow-through rate (profile visit after view) tells you whether traffic compounds into subscribers. Track these four per upload against your rolling median and you can usually classify a video's ceiling within a day."),
 ("Reading retention curves like an analyst","Retention graphs have grammar. A cliff at second one means a mismatch between promise and opening frame — fix packaging, not footage. A steady diagonal decline means pacing — tighten cuts or shorten duration. A dip at the midpoint followed by recovery signals a boring bridge section between hook and payoff — reorder segments. A spike near the end usually marks replay loops, which is gold: consider matching your final frame to your opening frame deliberately to amplify it. Train yourself to name the shape before prescribing the fix, because half of optimization advice fails by treating all drop-off as identical.")],
"collaboration-in-viral-video-production.html": [
 ("Structuring collabs so the velocity signal survives","Every collaboration splits your initial test cohort across two audiences, and algorithms read early engagement density — not raw reach. That means the best collab formats keep attention concentrated: rapid back-and-forth edits, split-screen reactions, or a shared series released simultaneously on both channels with cross-links in captions. Avoid long handoff structures where one creator disappears for thirty seconds; the audience transfer rarely completes and both retention curves sag. Before publishing, agree on who replies to comments in the first hour — dense early comment threads measurably extend distribution windows."),
 ("A lightweight agreement template","Most collab friction comes from unspoken expectations, so spend ten minutes writing down four things: deliverables and file specs (aspect ratios, caption styles, deadline dates), credit and tagging rules on every surface, a data-sharing commitment (each party screenshots 24-hour analytics for the other), and a kill clause allowing either creator to pull the piece if it misses agreed compliance checks. No lawyer needed — a shared note is enough — but the act of writing prevents the two classic failures: one partner promoting late, and disputes over who owns the resulting audience.")],
"colors-and-visual-design-in-viral-videos.html": [
 ("Palette choices that stop thumbs in feeds","At thumbnail scale, a feed is a wall of tiny rectangles, and what wins is contrast and color temperature separation from neighbors. High-chroma accents against desaturated backgrounds outperform busy multi-color frames; warm-forward palettes tend to pop against the cool interface chrome of most apps. Build a repeatable two-or-three-color signature per series so returning viewers recognize your video before reading the title — brand recognition at the scroll level is a legitimate ranking advantage because it lifts click-through and dwell time simultaneously."),
 ("Design consistency as a measurable asset","Run a simple audit: screenshot twelve consecutive thumbnails from your channel and check them at 100-pixel width. If you cannot tell which are yours without reading text, your visual system is decorative rather than functional. Standardize font weight, accent color placement and face-crop distance, then measure CTR change across the next six uploads. Creators who treat design consistency as an experiment rather than a preference typically see click-through improve faster than any editing technique, because packaging decisions compound across every impression.")],
"common-mistakes-in-creating-viral-videos.html": [
 ("Mistakes hiding in your metadata and posting habits","Production gets the attention, but some of the costliest errors live outside the edit: titles written for yourself instead of for search intent, hashtags copied wholesale from viral posts where they have saturated into noise, publishing times chosen around your schedule rather than your audience's actual activity window, and pinned comments left empty when they could carry the follow-up link or clarifying context. Each is a five-minute fix with disproportionate upside, and each shows up in analytics as a soft ceiling on otherwise good videos — the frustrating pattern of great content with flat numbers."),
 ("The sunk-cost trap: rescuing flops instead of learning from them","After weeks of work, creators routinely boost, re-cut and re-post failing videos hoping to force success. Data almost never rewards this. A video that missed its initial evaluation window has taught you something specific; the efficient move is a fifteen-minute post-mortem — name the metric that failed first, hypothesize why, convert the lesson into one rule for the next upload — then let the flop go. Channels that iterate forward grow roughly twice as fast as channels that keep resuscitating past work, because iteration frequency is the variable that actually correlates with improvement.")],
"cultural-impact-on-video-virality.html": [
 ("Cultural fit: why identical videos travel differently across regions","Sharing behaviour is culturally patterned. Collectivist audiences often share content that expresses group identity or family values, while individualist feeds reward content that lets one person signal wit or taste. Humor timing, authority cues and even acceptable levels of self-promotion vary sharply by market, so a video engineered for one culture's social norms can stall in another despite perfect technical execution. Before international pushes, run the concept through one local lens: does sharing this make the sender look good inside their social group? If the answer is unclear, localize the framing, not just the subtitles."),
 ("Practical localization workflow","Treat cultural adaptation as a checklist applied before publication, not a translation task afterwards: verify idioms and slang with a native speaker, check gesture and imagery associations (colors and symbols carry opposite meanings across markets), confirm holiday and event references land in the target region's calendar, and adjust pacing norms — some audiences read fast-talking edits as untrustworthy. Then monitor comment geography in your first 48 hours; unexpected regional hostility or confusion is your fastest correction signal, and small channels can course-correct within a single upload cycle.")],
"factors-affecting-video-virality-score.html": [
 ("Weighting factors by effort: a practical model","Not all inputs deserve equal engineering effort. Treat core multipliers — hook strength, share-worthy concept, completion-friendly length — as non-negotiable gates that must pass before polish begins; each multiplies everything downstream. Then treat modifiers — posting time, hashtag mix, thumbnail tweaks — as cheap adjustments applied last, since they shift outcomes by smaller percentages. Teams that invert this order burn weeks optimizing metadata on concepts that were never shareable. A quick sanity check: if fixing a factor only helps videos that already perform well, it is a modifier; if ignoring it caps every video regardless of quality, it is a multiplier."),
 ("Auditing your last ten videos against the factor list","Score each recent upload one to five on every factor in this guide, then plot factor scores against normalized virality outcomes. Your personal bottleneck jumps out immediately — for most creators it is concept-level shareability or the first three seconds, not the variables everyone obsesses over. Re-run the audit monthly; as soon as one factor stops differentiating your winners from your losers, its leverage is exhausted and your attention should rotate to the next constraint. This turns generic advice into a prioritized, channel-specific improvement queue.")],
"genres-that-boost-video-virality.html": [
 ("Matching genre to your real strengths","Genre tables tempt creators to chase whichever category is trending, but the highest expected value usually sits at the intersection of proven demand and your unfair advantage — domain access, on-camera style, editing skill or insider stories. A finance professional running comedy skits competes with full-time comedians; the same professional doing accurate, funny myth-busting owns a lane few can enter. Audit three candidate genres against two questions: can I produce this sustainably at weekly cadence, and is there a version only I could credibly make? Sustainable cadence plus unique access beats borrowed trend every quarter."),
 ("Hybrid genres outperform pure categories","The most durable viral formats are hybrids: education plus spectacle, documentary plus comedy, challenge plus craft. Pure-genre content competes inside crowded reference classes, while a hybrid creates its own comparison set — viewers describe it as that show that does X but also Y, which is exactly the phrase that triggers word-of-mouth sharing. To engineer one deliberately, take a format you can already produce weekly and graft a single element from an unrelated genre onto it, then test for two cycles before committing. Watch specifically for the share-motive sentence people use in comments; if they cannot name your hybrid quickly, the graft is not sticky yet.")],
"how-to-calculate-video-virality-score.html": [
 ("Worked example: scoring one video end to end","Take a clip with 40,000 views from a 5,000-follower account: 3,200 likes, 900 shares, 600 comments, average watch percentage 68%. Views-to-followers ratio is 8x, which alone clears the typical 2x threshold for out-of-pool performance. Shares per thousand views: 22.5 — strong, since most niches average under 10. Weighted naively (shares x3, comments x1.5, likes x1, completion x2), the composite lands roughly double the channel median: this video earned extended distribution because of the share mechanic, not luck. Record the components, not just the total — the breakdown is what tells you what to repeat."),
 ("Normalizing scores across platforms","A TikTok view and a YouTube view are not the same currency, so compare platforms on ratios, not absolutes: divide every interaction by views, then divide views by audience size. A 70% completion rate means roughly the same thing everywhere, and shares-per-thousand-views travels well too, while raw view counts do not. Keep one master sheet where each platform's videos are scored with the same normalized formula, and resist the temptation to tune weights per platform — the whole point of a composite score is comparability, and every extra free parameter makes your trend lines lie to you.")],
"optimizing-video-length-for-virality.html": [
 ("Duration experiments worth running","Length is one of the easiest variables to A/B honestly. Take a working format and cut three versions — 15, 30 and 60 seconds — same hook, same payoff, differing only in how much supporting material you keep. Compare completion percentage and absolute watch time together: platforms weigh both, and the crossover point where extra length stops earning its retention cost is your format's true ideal duration. Re-test quarterly, because attention norms drift faster than production habits; the sweet spot you found last year is a hypothesis, not a fact."),
 ("Segment length inside long-form videos","Even when total runtime is fixed, internal structure changes retention math. Front-load the promised payoff within the first third, then alternate intensity — high-energy demonstration, calmer explanation, high-energy again — because continuous intensity exhausts mobile viewers and continuous calm loses them. Use chapters or on-screen progress markers so viewers self-select segments worth finishing; partial watches of relevant segments still beat full watches of irrelevant ones on most platform quality models.")],
"the-impact-of-video-quality-on-virality.html": [
 ("Where quality pays off and where it doesn't","Quality spending follows diminishing returns that differ by surface. Audio clarity and lighting pay off almost everywhere because poor sound triggers instant swipes; 4K sensors rarely matter once a platform compresses your file anyway. What consistently moves metrics is perceived intentionality — clean framing, readable text, deliberate pacing — which costs editing discipline, not gear. The classic failure mode is creators buying cameras to compensate for weak hooks: sharper pixels never rescued a concept that failed its first three seconds."),
 ("A quality bar you can actually enforce","Define minimum standards per element — audio peaks consistent and intelligible on phone speakers, faces lit enough to read emotion at thumbnail size, zero dead frames longer than two seconds, captions legible at 60% screen size — and gate publication on passing them. A binary checklist beats subjective is-this-good-enough debates, removes decision fatigue, and keeps quality conversations about viewer experience rather than equipment envy. Review the bar quarterly against your top and bottom performing videos; prune any standard that no longer separates winners from losers.")],
"the-importance-of-a-strong-call-to-action.html": [
 ("Sequencing CTAs with viewer motivation","A CTA lands only when the viewer has just received value and still has attention to spare. The reliable sequence: earn the payoff, plant the ask within five seconds of it, and keep the ask singular — follow for part two beats like, comment, subscribe and share. Placement also varies by platform behavior: Shorts and Reels users respond to verbal asks timed before the loop restarts, while longer-form audiences tolerate an on-screen card during the outro. Whatever the surface, measure CTA lift by comparing follower-gain-per-thousand-views on videos with and without the ask — the number settles the debate faster than opinion ever will."),
 ("CTAs that create the next video's audience","The strongest call-to-action is one that sets up your follow-up: next week we test the twenty-dollar microphone — follow so you see the result. That converts a request into a promise, giving viewers a reason tied to their own curiosity rather than your vanity metric. Rotate three recurring asks across a series so regulars learn the rhythm, and pin a comment carrying the same promise on every upload, because the pinned thread is read disproportionately by exactly the high-intent viewers most likely to convert.")],
"timing-of-video-release-and-virality.html": [
 ("Timing beyond the generic post-at-6pm chart","Platform-wide heat maps describe average crowds; your channel has its own micro-climate. Check when your followers are active in the app (available natively on most platforms), then test releasing 30 to 60 minutes before that peak so the video accumulates early engagement right as your audience opens the app. Layer event-awareness on top: news cycles, payday weekends, seasonal moods and platform feature launches all shift baseline activity, and a great concept published against a major cultural moment competes for the same attention slot. Timing will never rescue weak content, but it decides how many people see your good content first."),
 ("Release-day operations most creators skip","Publishing is not the finish line — the first hour is a managed window. Line up replies to every early comment, seed the video into relevant community spaces where you already participate, and add the pinned comment with context or a follow-up link before promotion begins. These actions raise engagement density during exactly the interval the algorithm uses for its distribution decision, at zero production cost. Schedule your own availability accordingly: a great release time you are asleep for wastes the timing work entirely.")],
"title-length-and-its-impact-on-video-virality.html": [
 ("Writing titles that survive truncation","Most surfaces show 40 to 60 characters before ellipsis, and mobile previews show fewer, so front-load the load-bearing words: put the subject and the tension first, qualifiers last. Compare How We Tested 12 Microphones for Street Interviews versus Street Interview Mic Test: The 12 Best Sounds — same information, but the second delivers its payload before truncation. Then check keyword alignment: the phrase someone would type to find your video should appear naturally in the first half. Finally, read your title aloud next to your opening line; redundancy between them wastes persuasion space, while complementary framing doubles it."),
 ("Title formulas, tested honestly","Formulas (number plus object plus outcome, question plus stakes, negation plus surprise) are starting hypotheses, not laws. Test them the scientific way: hold format and topic class constant, change only the title pattern, and compare click-through across at least six pairs before believing a winner. Beware the curiosity-gap arms race — clickbait titles that overpromise depress watch percentage, which drags the same distribution engine you were trying to trick. The durable optimum is the title that attracts exactly the viewers your video satisfies.")],
"top-10-video-virality-tools.html": [
 ("Choosing tools by the job, not the hype","Before subscribing to anything, name the decision you need help making: predicting performance before upload, diagnosing it after, or monitoring competitors continuously. Prediction tools are least reliable and most marketed; diagnostic dashboards built from native analytics are free and usually sufficient; competitor trackers save the most hours. With that triage done, pick the smallest stack that covers your actual jobs — typically one native-analytics habit, one spreadsheet template, and at most one paid tracker — and give every tool a 30-day trial ending in a keep-or-kill decision tied to a concrete workflow change it enabled."),
 ("Data hygiene rules every tool depends on","No dashboard fixes inconsistent recording. Decide your metric definitions once (what counts as a view, over what window, shares per thousand views normalized how), log uploads within 48 hours while platform data is accessible, and keep one source of truth rather than three competing spreadsheets. Export raw numbers monthly — platforms delete history — and annotate entries with what you changed, because unannotated data turns every retrospective into guesswork about your own channel.")],
"understanding-audience-feedback-for-virality.html": [
 ("Closing the feedback loop with a meta-metric","Collecting feedback fails when insights never reach the production checklist, so formalize one number: the percentage of your last ten videos that contain at least one element requested in comments. If it is below 30%, you are listening but not acting; if it is near 100%, you may be over-fitting to the loudest voices. Review requests monthly in three buckets — repeated signals (build them), one-off smart ideas (test them), and taste-only complaints (log and ignore). The bucketing matters more than volume: audiences reward creators who visibly implement suggestions, and reply-thread visibility itself drives comment engagement, which feeds the distribution signal chain."),
 ("Questions that generate better feedback than comments","Comments skew toward extremes; structured prompts surface the middle. Run quarterly polls asking one thing (which upcoming topic would you send to a friend?), pin a question inviting criticism (what would have made this more useful?), and interview five superfans for fifteen minutes each — their language doubles as future title and hook copy. Triangulate before acting: a theme appearing in comments, polls and interviews simultaneously is a green light; a theme present only in comments is a vocal minority.")],
}

for f, secs in ADDS.items():
    html = open(f).read()
    add = "".join('\n<h2 class="text-2xl font-bold mt-8 mb-3">%s</h2>\n<p class="mb-4">%s</p>' % (h, b) for h, b in secs)
    i = html.rindex('</article>')
    html = html[:i] + add + '\n' + html[i:]
    open(f, 'w').write(html)
    print(words(f), f)
